openapi: 3.1.0
info:
  title: Car Rental API
  description: OpenAPI documentation for Car Rental service
  version: v1
servers:
  - url: http://localhost:8080
    description: Generated server url
paths:
  /api/bookings/confirm:
    post:
      tags:
        - car-rental-booking-controller
      operationId: confirmBooking
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CarRentalBooking"
        required: true
      responses:
        "404":
          description: Not Found
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ApiResponseVoid"
        "400":
          description: Bad Request
          content:
            '*/*':
              schema:
                oneOf:
                  - $ref: "#/components/schemas/ApiResponseVoid"
                  - $ref: "#/components/schemas/ApiResponseMapStringString"
        "500":
          description: Internal Server Error
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ApiResponseVoid"
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/CarRentalBooking"
  /api/bookings/{id}:
    get:
      tags:
        - car-rental-booking-controller
      operationId: getBookingDetails
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        "404":
          description: Not Found
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ApiResponseVoid"
        "400":
          description: Bad Request
          content:
            '*/*':
              schema:
                oneOf:
                  - $ref: "#/components/schemas/ApiResponseVoid"
                  - $ref: "#/components/schemas/ApiResponseMapStringString"
        "500":
          description: Internal Server Error
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ApiResponseVoid"
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/CarRentalBooking"
components:
  schemas:
    ApiResponseMapStringString:
      type: object
      properties:
        success:
          type: boolean
        message:
          type: string
        data:
          type: object
          additionalProperties:
            type: string
        timestamp:
          type: string
          format: date-time
        error:
          type: string
    ApiResponseVoid:
      type: object
      properties:
        success:
          type: boolean
        message:
          type: string
        data: {}
        timestamp:
          type: string
          format: date-time
        error:
          type: string
    CarRentalBooking:
      type: object
      properties:
        id:
          type: integer
          format: int64
        drivingLicenseNumber:
          type: string
        age:
          type: integer
          format: int32
        reservationStartDate:
          type: string
          format: date
        reservationEndDate:
          type: string
          format: date
        rentalPrice:
          type: number
          format: double
        carSegment:
          type: string
          enum:
            - SMALL
            - MEDIUM
            - LARGE
            - EXTRA_LARGE
